
package view;

import controller.Consults;

/**
 *
 * @author Alex
 */
public class ConsultsPanel extends javax.swing.JPanel {

    private final Consults c;
    
    public ConsultsPanel() {
        initComponents();
        
        c = new Consults(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cbConsults = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        cbContinents = new javax.swing.JComboBox<>();
        btnConsult = new javax.swing.JButton();
        lblQuestion = new javax.swing.JLabel();
        lblAnswer = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        setOpaque(false);
        setLayout(new java.awt.BorderLayout());

        topPanel.setOpaque(false);
        topPanel.setPreferredSize(new java.awt.Dimension(100, 120));
        topPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 5));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Seleccione la consulta:");
        jLabel2.setPreferredSize(new java.awt.Dimension(150, 16));
        topPanel.add(jLabel2);

        cbConsults.setForeground(new java.awt.Color(0, 0, 0));
        cbConsults.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbConsults.setOpaque(false);
        cbConsults.setPreferredSize(new java.awt.Dimension(500, 30));
        topPanel.add(cbConsults);

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Seleccione el Continente:");
        jLabel1.setPreferredSize(new java.awt.Dimension(150, 16));
        topPanel.add(jLabel1);

        cbContinents.setForeground(new java.awt.Color(0, 0, 0));
        cbContinents.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbContinents.setOpaque(false);
        cbContinents.setPreferredSize(new java.awt.Dimension(200, 30));
        topPanel.add(cbContinents);

        btnConsult.setBackground(new java.awt.Color(204, 102, 0));
        btnConsult.setForeground(new java.awt.Color(255, 255, 255));
        btnConsult.setText("Consultar");
        btnConsult.setBorder(null);
        btnConsult.setBorderPainted(false);
        btnConsult.setFocusPainted(false);
        btnConsult.setPreferredSize(new java.awt.Dimension(200, 30));
        topPanel.add(btnConsult);

        lblQuestion.setForeground(new java.awt.Color(0, 0, 0));
        lblQuestion.setPreferredSize(new java.awt.Dimension(220, 30));
        topPanel.add(lblQuestion);

        lblAnswer.setForeground(new java.awt.Color(0, 0, 0));
        lblAnswer.setPreferredSize(new java.awt.Dimension(220, 30));
        topPanel.add(lblAnswer);

        add(topPanel, java.awt.BorderLayout.PAGE_START);

        jPanel1.setOpaque(false);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(700, 350));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table);

        jPanel1.add(jScrollPane1);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnConsult;
    public javax.swing.JComboBox<String> cbConsults;
    public javax.swing.JComboBox<String> cbContinents;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lblAnswer;
    public javax.swing.JLabel lblQuestion;
    public javax.swing.JTable table;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables
}
