
package view;

import controller.NewCountry;

/**
 *
 * @author Alex
 */
public class NewCountryView extends javax.swing.JPanel {

    private final NewCountry nc;
    public NewCountryView() {
        initComponents();
        
        nc = new NewCountry(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        OptionsPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbCountries = new javax.swing.JComboBox<>();
        rbAddContinent = new javax.swing.JRadioButton();
        txtNewContinent = new javax.swing.JTextField();
        btnAddContinent = new javax.swing.JButton();
        MainPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        bottomPanel = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        dataPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtCountry = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtResidents = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtSurface = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtContinent = new javax.swing.JTextField();

        setMinimumSize(new java.awt.Dimension(79, 79));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(660, 480));
        setLayout(new java.awt.BorderLayout());

        OptionsPanel.setBackground(new java.awt.Color(255, 255, 255));
        OptionsPanel.setForeground(new java.awt.Color(255, 255, 255));
        OptionsPanel.setOpaque(false);
        OptionsPanel.setPreferredSize(new java.awt.Dimension(200, 480));
        OptionsPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 15, 15));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Seleccione Continente:");
        OptionsPanel.add(jLabel1);

        cbCountries.setForeground(new java.awt.Color(0, 0, 0));
        cbCountries.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbCountries.setBorder(null);
        cbCountries.setOpaque(false);
        cbCountries.setPreferredSize(new java.awt.Dimension(170, 30));
        OptionsPanel.add(cbCountries);

        rbAddContinent.setForeground(new java.awt.Color(0, 0, 0));
        rbAddContinent.setText("Nuevo Continente");
        rbAddContinent.setContentAreaFilled(false);
        rbAddContinent.setPreferredSize(new java.awt.Dimension(170, 30));
        OptionsPanel.add(rbAddContinent);

        txtNewContinent.setForeground(new java.awt.Color(0, 0, 0));
        txtNewContinent.setOpaque(false);
        txtNewContinent.setPreferredSize(new java.awt.Dimension(170, 30));
        OptionsPanel.add(txtNewContinent);

        btnAddContinent.setBackground(new java.awt.Color(0, 102, 153));
        btnAddContinent.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnAddContinent.setForeground(new java.awt.Color(255, 255, 255));
        btnAddContinent.setText("Agregar Continente");
        btnAddContinent.setBorder(null);
        btnAddContinent.setFocusPainted(false);
        btnAddContinent.setPreferredSize(new java.awt.Dimension(170, 40));
        OptionsPanel.add(btnAddContinent);

        add(OptionsPanel, java.awt.BorderLayout.LINE_START);

        MainPanel.setBackground(new java.awt.Color(204, 204, 204));
        MainPanel.setOpaque(false);
        MainPanel.setLayout(new java.awt.BorderLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Inserte los datos del nuevo País");
        jLabel2.setPreferredSize(new java.awt.Dimension(183, 40));
        MainPanel.add(jLabel2, java.awt.BorderLayout.PAGE_START);

        bottomPanel.setOpaque(false);
        bottomPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 30, 15));

        btnSave.setBackground(new java.awt.Color(0, 153, 51));
        btnSave.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Guardar");
        btnSave.setBorder(null);
        btnSave.setBorderPainted(false);
        btnSave.setPreferredSize(new java.awt.Dimension(120, 40));
        bottomPanel.add(btnSave);

        btnCancel.setBackground(new java.awt.Color(153, 0, 153));
        btnCancel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Cancelar");
        btnCancel.setBorder(null);
        btnCancel.setBorderPainted(false);
        btnCancel.setPreferredSize(new java.awt.Dimension(120, 40));
        bottomPanel.add(btnCancel);

        MainPanel.add(bottomPanel, java.awt.BorderLayout.PAGE_END);

        dataPanel.setOpaque(false);
        dataPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 20));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nombre del País:");
        jLabel3.setPreferredSize(new java.awt.Dimension(120, 30));
        dataPanel.add(jLabel3);

        txtCountry.setForeground(new java.awt.Color(0, 0, 0));
        txtCountry.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtCountry.setOpaque(false);
        txtCountry.setPreferredSize(new java.awt.Dimension(350, 30));
        dataPanel.add(txtCountry);

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Nº Habitantes:");
        jLabel4.setPreferredSize(new java.awt.Dimension(120, 30));
        dataPanel.add(jLabel4);

        txtResidents.setForeground(new java.awt.Color(0, 0, 0));
        txtResidents.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtResidents.setOpaque(false);
        txtResidents.setPreferredSize(new java.awt.Dimension(350, 30));
        dataPanel.add(txtResidents);

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Superficie km2:");
        jLabel5.setPreferredSize(new java.awt.Dimension(120, 30));
        dataPanel.add(jLabel5);

        txtSurface.setForeground(new java.awt.Color(0, 0, 0));
        txtSurface.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtSurface.setOpaque(false);
        txtSurface.setPreferredSize(new java.awt.Dimension(350, 30));
        dataPanel.add(txtSurface);

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Continente:");
        jLabel6.setPreferredSize(new java.awt.Dimension(120, 30));
        dataPanel.add(jLabel6);

        txtContinent.setForeground(new java.awt.Color(0, 0, 0));
        txtContinent.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtContinent.setOpaque(false);
        txtContinent.setPreferredSize(new java.awt.Dimension(350, 30));
        dataPanel.add(txtContinent);

        MainPanel.add(dataPanel, java.awt.BorderLayout.CENTER);

        add(MainPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel MainPanel;
    public javax.swing.JPanel OptionsPanel;
    private javax.swing.JPanel bottomPanel;
    public javax.swing.JButton btnAddContinent;
    public javax.swing.JButton btnCancel;
    public javax.swing.JButton btnSave;
    public javax.swing.JComboBox<String> cbCountries;
    public javax.swing.JPanel dataPanel;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public javax.swing.JRadioButton rbAddContinent;
    public javax.swing.JTextField txtContinent;
    public javax.swing.JTextField txtCountry;
    public javax.swing.JTextField txtNewContinent;
    public javax.swing.JTextField txtResidents;
    public javax.swing.JTextField txtSurface;
    // End of variables declaration//GEN-END:variables
}
